spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
    properties:
      hibernate.format_sql : true
    show-sql: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/template?serverTimezone=Asia/Seoul
#    username: root
#    password: 'xcz119'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://testdbms.cwhwqtlljfje.ap-northeast-2.rds.amazonaws.com:3306/testdbms?serverTimezone=Asia/Seoul
    username: admin
    password: 'rhkreodid'
  vonage:
    api:
      key: 3752d3ca
      secret: 'dmuM2sys8D6trjo7'
    from:
      number: +821031267242
springdoc:
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method # alpha(알파벳 오름차순), method(HTTP 메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
    model-converters:
      pageable-converter:
        enabled: true